services:
  web_service:
    build: .
    container_name: classification
    command: uvicorn AppFiles.main:FastAPI_Object --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
    volumes:
      - ./AppFiles:/ContainerWD/AppFiles